In [1]:
from dismal import blocking, s_matrix
import numpy as np

In [2]:
callset = blocking.CallSet(zarr_path="../../brenthis_test/test_vcf.zarr")

In [3]:
bd = blocking.BlocksDictionary(callset, block_len=100, gap=5_000, max_missing=2)

In [4]:
samples = list(bd.samples())
species = ["BD", "BI", "BD", "BI", "BD", "BD", "BD", "BD", "BI", "BI", "BD", "BI", "BI"]

samples_dict = dict(zip(samples, species))

In [6]:
sm = s_matrix.SMatrix()
sm.from_blockdict(blockdict=bd, samples_dict=samples_dict)

array([[ 4034,   284,   307,   321,   335,   388,   389,   394,   475,
          403,   445,   518,   471,   474,   464,   523,   513,   497,
          479,   473,   500,   509,   466,   490,   490,   446,   492,
          482,   452,   413,   422,   423,   462,   458,   428,   401,
          349,   305,   330,   321,   287,   286,   263,   225,   193,
          205,   164,   143,   118,   130,    92,    99,    73,    70,
           56,    38,    39,    46,    36,    20,    27,    13,    22,
           18,    18,    19,     9,    10,     9,     7,     4,     4,
            4,     0,     1,     4,     2,     2,     2,     3,     2,
            0,     0,     1,     0,     0,     0],
       [ 6246,   770,   653,   553,   473,   454,   384,   377,   330,
          286,   245,   194,   226,   214,   183,   180,   153,   174,
          143,   146,   148,   137,   125,   134,   124,   120,   148,
          131,   137,   117,   139,   134,   128,   127,   115,   110,
          111,    97,    9

In [6]:
arr1 = np.array([0,1,-1])
arr2 = np.array([0,1,-1])

arr1_missing = np.where(arr1 < 0)[0]
arr2_missing = np.where(arr2 < 0)[0]

In [8]:
arr2_missing

array([2])

In [9]:
np.concatenate(arr1_missing, arr2_missing)

TypeError: only integer scalar arrays can be converted to a scalar index

In [12]:
np.concatenate([arr1_missing, arr2_missing])

array([2, 2])