In [1]:
! pip install -e ..
from dismal import demography, preprocess, likelihood, simulate, matrices
import numpy as np

Obtaining file:///Users/s2341012/Dropbox/DISMaL_chapter/DISMaL
  Preparing metadata (setup.py) ... done
  Attempting uninstall: dismal
    Found existing installation: dismal 0.1
    Uninstalling dismal-0.1:
      Successfully uninstalled dismal-0.1
  Running setup.py develop for dismal


In [2]:
from dismal.utils import _opt_to_model_params, _model_to_opt_params
model_params1 = {"a":1.0, "b":1.0, "c1":1.0, "c2":1.0, "tau1":1.0, "tau0":2.0, "m1":0.0, "m2":0.0, "m1_prime":0.0, "m2_prime":0.0, "theta":5.0}
opt_params1 = {"theta0":5.0, "theta1":5.0, "theta2":5.0, "theta1_prime":5.0, "theta2_prime":5.0, "t1":5.0, "v":5.0, "m1_star":0.0, "m2_star":0.0, "m1_prime_star":0.0, "m2_prime_star":0.0}
model_params2 = {"a":1.0, "b":2.0, "c1":1, "c2":1.0, "tau1":1.0, "tau0":2.0, "m1":0.1, "m2":0.1, "m1_prime":0.2, "m2_prime":0.2, "theta":2.0}
opt_params2 = {"theta0":2.0, "theta1":2.0, "theta2":4.0, "theta1_prime":2.0, "theta2_prime":2.0, "t1":2.0, "v":2.0, "m1_star":0.1, "m2_star":0.2, "m1_prime_star":0.2, "m2_prime_star":0.2}

In [3]:
_opt_to_model_params(opt_params1)

{'theta': 5.0,
 'a': 1.0,
 'b': 1.0,
 'c1': 1.0,
 'c2': 1.0,
 'tau1': 1.0,
 'tau0': 2.0,
 'm1': 0.0,
 'm2': 0.0,
 'm1_prime': 0.0,
 'm2_prime': 0.0}

In [12]:
s=0
a=2.803066955313531
b=8.86450716120465e-11
c1=0.8610691592835797
c2=1.4641559116241056
tau1=8.86450716120465e-11
tau0=1.7621783109489693
m1=0
m2=0
m1_prime=0
m2_prime=0
theta=1.128094299902516
state=2

In [13]:
likelihood._pdf_s(s=0, a=2.803066955313531, b=8.86450716120465e-11, c1=0.8610691592835797, c2=1.4641559116241056, tau1=8.86450716120465e-11, tau0=1.7621783109489693, m1=0, m2=0, m1_prime=0, m2_prime=0, theta=1.128094299902516, state=2)

AssertionError: Probabilities outside range [0,1]: p=1.0098777122285558, term1=-6.05434591349763e-11, term2=-0.999999999739457, term3=0.00987771242855566 for parameters [0, 2.803066955313531, 8.86450716120465e-11, 0.8610691592835797, 1.4641559116241056, 8.86450716120465e-11, 1.7621783109489693, 0, 0, 0, 0, 1.128094299902516, 2]

In [17]:
q1 = matrices.GeneratorMatrix(m1_prime=m1_prime, m2_prime=m2_prime, c1=c1, c2=c2, matrix_type="Q1")

In [18]:
q2 = matrices.GeneratorMatrix(m1=m1, m2=m2, b=b, matrix_type="Q2")

In [19]:
q3 = matrices.GeneratorMatrix(a=a, matrix_type="Q3")

In [20]:
p1 = matrices.TransitionMatrix(q1, q2, q3, t=tau1, tau1=tau1, tau0=tau0)
p2 = matrices.TransitionMatrix(q1, q2, q3, t=(tau0-tau1), tau1=tau1, tau0=tau0)

In [25]:
p1

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 1.02947679e-10]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 6.05434646e-11]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]

----

In [ ]:
likelihood._pdf_s()

In [2]:
s_counts = simulate.msprime_simulate(a=1, b=1, c1=1, c2=1, tau1=1, tau0=2, m1=0, m2=0, m1_prime=0, m2_prime=0, theta=0.01, N=10000, num_replicates=1000, block_len=150)

In [5]:
demography.Demography(X=s_counts, model="isolation").infer_parameters(theta_initial=0.01)

Parameters: {'theta': 0.01, 'a': 1.0, 'b': 1.0, 'c1': 1.0, 'c2': 1.0, 'tau1': 2.0, 'tau0': 2.0}, -lnL: 20220.836831122477
Parameters: {'theta': 0.01000001, 'a': 0.9999990000010001, 'b': 0.9999990000010001, 'c1': 0.9999990000010001, 'c2': 0.9999990000010001, 'tau1': 1.9999980000020001, 'tau0': 1.9999980000020001}, -lnL: 20220.836831122473
Parameters: {'theta': 0.01, 'a': 1.000001, 'b': 1.0, 'c1': 1.0, 'c2': 1.0, 'tau1': 2.0, 'tau0': 2.0}, -lnL: 20220.835297075686
Parameters: {'theta': 0.01, 'a': 1.0, 'b': 1.000001, 'c1': 1.0, 'c2': 1.0, 'tau1': 2.0, 'tau0': 2.0}, -lnL: 20220.836831122477
Parameters: {'theta': 0.01, 'a': 1.0, 'b': 1.0, 'c1': 1.000001, 'c2': 1.0, 'tau1': 2.0, 'tau0': 2.0}, -lnL: 20220.836358852295
Parameters: {'theta': 0.01, 'a': 1.0, 'b': 1.0, 'c1': 1.0, 'c2': 1.000001, 'tau1': 2.0, 'tau0': 2.0}, -lnL: 20220.836399364296
Parameters: {'theta': 0.01, 'a': 1.0, 'b': 1.0, 'c1': 1.0, 'c2': 1.0, 'tau1': 2.000001, 'tau0': 2.000001}, -lnL: 20220.836259520987
Parameters: {'theta'

AssertionError: Probabilities outside range [0,1]: p=1.0098777122285558, term1=-6.05434591349763e-11, term2=-0.999999999739457, term3=0.00987771242855566 for parameters [0, 2.803066955313531, 8.86450716120465e-11, 0.8610691592835797, 1.4641559116241056, 8.86450716120465e-11, 1.7621783109489693, 0, 0, 0, 0, 1.128094299902516, 2]

In [4]:
s_counts

[{0: 577, 1: 235, 2: 112, 3: 45, 4: 18, 5: 5, 6: 5, 7: 2, 8: 1},
 {0: 604, 1: 236, 2: 102, 3: 30, 4: 18, 5: 5, 6: 4, 7: 1},
 {0: 37,
  1: 109,
  2: 182,
  3: 187,
  4: 172,
  5: 132,
  6: 82,
  7: 54,
  8: 15,
  9: 18,
  10: 9,
  11: 3}]