In [1]:
! pip install -e ..

Obtaining file:///Users/s2341012/Dropbox/DISMaL_chapter/DISMaL
  Preparing metadata (setup.py) ... done
  Attempting uninstall: dismal
    Found existing installation: dismal 0.1
    Uninstalling dismal-0.1:
      Successfully uninstalled dismal-0.1
  Running setup.py develop for dismal


In [2]:
from dismal.likelihood_matrix import LikelihoodMatrix
from dismal.generator_matrices import GeneratorMatrix
from dismal.utils import expect_states1_2, expect_state_3
import numpy as np

In [28]:
one_by_ten_S = np.array([
    [1]*10,
    [1]*10,
    [1]*10,
])

In [29]:
params = {'theta0': 5,
                  'theta1': 5,
                  'theta2': 5,
                  'theta1_prime': 5,
                  'theta2_prime': 5,
                  't1': 5,
                  'v': 5}

In [30]:
lm = LikelihoodMatrix(params, one_by_ten_S)

In [31]:
lm.matrix

array([[ 1.79175947,  1.97408103,  2.15640258,  2.33872414,  2.5210457 ,
         2.70336725,  2.88568881,  3.06801037,  3.25033192,  3.43265348],
       [ 1.79175947,  1.97408103,  2.15640258,  2.33872414,  2.5210457 ,
         2.70336725,  2.88568881,  3.06801037,  3.25033192,  3.43265348],
       [11.79175947,  9.40913167,  7.71375133,  6.41714572,  5.40060132,
         4.59848253,  3.96867307,  3.48147678,  3.11448286,  2.84985184]])

In [32]:
lm.gamma

0.2

In [33]:
lm.alpha_matrix()

array([[ 0.16625354,  0.13647899,  0.10856843,  0.08186691,  0.05746395,
         0.03712815,  0.02197473,  0.01190843,  0.00592128,  0.00271084],
       [ 0.16625354,  0.13647899,  0.10856843,  0.08186691,  0.05746395,
         0.03712815,  0.02197473,  0.01190843,  0.00592128,  0.00271084],
       [-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ]])

In [40]:
lm.pij2

array([[0.36787944, 0.        , 0.        , 0.63212056],
       [0.        , 0.36787944, 0.        , 0.63212056],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [46]:
lm.matrix.sum()

110.98948608717939

In [47]:
lm.matrix

array([[ 1.79175947,  1.97408103,  2.15640258,  2.33872414,  2.5210457 ,
         2.70336725,  2.88568881,  3.06801037,  3.25033192,  3.43265348],
       [ 1.79175947,  1.97408103,  2.15640258,  2.33872414,  2.5210457 ,
         2.70336725,  2.88568881,  3.06801037,  3.25033192,  3.43265348],
       [11.79175947,  9.40913167,  7.71375133,  6.41714572,  5.40060132,
         4.59848253,  3.96867307,  3.48147678,  3.11448286,  2.84985184]])