In [6]:
! pip install -e ..
from dismal.stochastic_matrices import GeneratorMatrix
import numpy as np
from scipy import linalg
from likelihood import p_matrix

Obtaining file:///Users/s2341012/Dropbox/DISMaL_chapter/DISMaL
  Preparing metadata (setup.py) ... done
  Attempting uninstall: dismal
    Found existing installation: dismal 0.1
    Uninstalling dismal-0.1:
      Successfully uninstalled dismal-0.1
  Running setup.py develop for dismal


In [9]:
params = [5,5,5,5,5,5,5,0,0,0,0]
q1, q2, q3 = GeneratorMatrix.from_params(params)

In [ ]:
[[5,5,5,5,5,5,5,0,0,0,0],
                      [5,5,5,5,5,5,5,5,5,5,5],
                      [0,0,0,0,0,0,0,0,0,0,0]]

In [26]:
params = [0.1,0.1,0.1,0.1,0.1,0,0,0,0,0,0]
q1, q2, q3 = GeneratorMatrix.from_params(params)
g, eigenvalues = q1.eigen()
ginv = linalg.inv(g)
t = 0
p_matrix(g, ginv, eigenvalues, t)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
import itertools

In [33]:
popsizes = [0.01, 0.1, 1, 10, 100]
mig_rates = [0, 0.0001, 0.01, 1, 10]
[i for i in itertools.permutations(popsizes, 3)][0]

(0.01, 0.1, 1)

In [2]:
from dismal.generator_matrices import GeneratorMatrix
GeneratorMatrix(matrix_type="Q1", theta1=1, theta1_prime=2, theta2_prime=3, m1_prime_star=1.5, m2_prime_star=2.5)

[[-1.25        0.          0.75        0.5       ]
 [ 0.         -1.16666667  0.83333333  0.33333333]
 [ 0.41666667  0.375      -0.79166667  0.        ]
 [ 0.          0.          0.          0.        ]]

In [11]:
import numpy as np
GeneratorMatrix(matrix_type="Q2", theta1=1, theta2=3, m1_star=1.5, m2_star=2.5)

[[-2.5         0.          1.5         1.        ]
 [ 0.         -1.16666667  0.83333333  0.33333333]
 [ 0.41666667  0.75       -1.16666667  0.        ]
 [ 0.          0.          0.          0.        ]]

In [15]:
np.array([[-(2.5), 0, 1.5, 1],
                           [0, -(1/3+5/6), 5/6, 1/3],
                           [5/12, 3/4, -((1.5+(5/6))/2), 0],
                           [0, 0, 0, 0]])

array([[-2.5       ,  0.        ,  1.5       ,  1.        ],
       [ 0.        , -1.16666667,  0.83333333,  0.33333333],
       [ 0.41666667,  0.75      , -1.16666667,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [16]:
from dismal.likelihood import alpha_matrix

In [20]:
alpha_matrix([1,1,0], s_vals=[0,1,2, 3, 4, 5, 6], t1=1)

array([[0.43233236, 0.14849854, 0.04041545, 0.00892978, 0.00164541,
        0.00025881, 0.00003542],
       [0.43233236, 0.14849854, 0.04041545, 0.00892978, 0.00164541,
        0.00025881, 0.00003542],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])